// Project_002.cpp : Defines the entry point for the console application.
//
// Adrian Dale 09/01/2009
//
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// Find the sum of all the even-valued terms in the sequence which do not exceed four million.
//
// Answer 4613732

#include <iostream>

using namespace std;

int main(int argc, char* argv[])
{
	// Start from 1 1 so that we include 2 in our sum.
	// Note that to start from 1 we'd need a=0 b=1
	int a = 1;
	int b = 1;
	int fib = 0;

	int sum = 0;

	// This is the naive solution but since we only care about
	// up to 4000000 it takes miliseconds to run, anyway.
	while ( (fib = a + b) < 4000000 )
	{
		a = b;
		b = fib;

		if ( fib % 2 == 0 )
			sum += fib;
	}

	cout << "sum=" << sum << endl;

	return 0;
}
